#!/bin/bash
#PBS -V
#PBS -l walltime=96:00:00
#PBS -l nodes=1:ppn=4
#PBS -j oe

cd $PBS_O_WORKDIR

echo " "
echo "Job started on `hostname` at `date`"

mpirun -np 4 /home/mcurnan/GGA+U_Corr/TestProj1_Code/example_LaCoO3/0/La/pw_plusPP_Lad1.x -inp LaCoO_U0_init.in
mkdir alpha
cp -r init/* alpha/
mpirun -np 4 /home/mcurnan/GGA+U_Corr/TestProj1_Code/example_LaCoO3/0/La/pw_plusPP_Lad1.x -inp LaCoO_U0_a-15.in
\rm -rf alpha/*
cp -r init/* alpha/
mpirun -np 4 /home/mcurnan/GGA+U_Corr/TestProj1_Code/example_LaCoO3/0/La/pw_plusPP_Lad1.x -inp LaCoO_U0_a-10.in
\rm -rf alpha/*
cp -r init/* alpha/
mpirun -np 4 /home/mcurnan/GGA+U_Corr/TestProj1_Code/example_LaCoO3/0/La/pw_plusPP_Lad1.x -inp LaCoO_U0_a-5.in
\rm -rf alpha/*
cp -r init/* alpha/
mpirun -np 4 /home/mcurnan/GGA+U_Corr/TestProj1_Code/example_LaCoO3/0/La/pw_plusPP_Lad1.x -inp LaCoO_U0_a0.in
\rm -rf alpha/*
cp -r init/* alpha/
mpirun -np 4 /home/mcurnan/GGA+U_Corr/TestProj1_Code/example_LaCoO3/0/La/pw_plusPP_Lad1.x -inp LaCoO_U0_a5.in
\rm -rf alpha/*
cp -r init/* alpha/
mpirun -np 4 /home/mcurnan/GGA+U_Corr/TestProj1_Code/example_LaCoO3/0/La/pw_plusPP_Lad1.x -inp LaCoO_U0_a10.in
\rm -rf alpha/*
cp -r init/* alpha/
mpirun -np 4 /home/mcurnan/GGA+U_Corr/TestProj1_Code/example_LaCoO3/0/La/pw_plusPP_Lad1.x -inp LaCoO_U0_a15.in
\rm -rf alpha/*

echo " "
echo "Job Ended on `hostname` at `date`"
echo " "
#end